#!/usr/bin/env python3
# v2.31 IP-sanitize rename: Zerg->Skarn, Protoss->Auraxis + derived names.
# Ordered regex sweep over src2/**/*.js. Prints residual trademark hits.
import re, pathlib

ROOT = pathlib.Path('/Users/davidpence/scc-work')
FILES = sorted(ROOT.glob('src2/**/*.js'))

# Identifier-safe boundaries: (?<![\w'])X(?![\w']) matches bare word token
def w(x): return r"(?<![\w'])" + x + r"(?![\w'])"

RULES = [
  # ---- distinctive lore / trademark phrases (longest first) ----
  (r"Xel'Naga-bane", 'Vexis'),
  (r"Council of the Templar", 'The Convocation'),
  (r'Templar Archives', 'Psi Vault'),
  (r'templarArchives', 'psiVault'),
  (r'Dark Templar Research', 'Nightblade Veil'),
  (r'High Templar', 'Stormcaller'),
  (r'highTemplar', 'stormcaller'),
  (r'htemplar', 'caller'),
  (r'Dark Archon', 'Umbral'),
  (r'darkArchonMerge', 'umbralConvergence'),
  (r'darkArchon', 'umbral'),
  (r'Dark Templar', 'Nightblade'),
  (r'darkTemplar', 'nightblade'),
  (r'Archon', 'Radiant'),
  (r'archon', 'radiant'),
  (r'Templar', 'Adept'),
  (r'Overmind', 'Hive Crown'),
  (r'Cerebrate', 'Broodlord'),
  (r'Kerrigan', 'Vexara'),
  (r'BROOD Mother Kerra', 'BROODMOTHER Vexara'),
  (r'Daelaam', 'Auraxis'),
  (r'\bAiur\b', 'Auraxis'),
  (r'\bZerus\b', 'Skar'),
  (r'Mar Sara', 'Outpost Kesh'),
  (r'Korhal', 'Outpost Kesh'),
  (r'Rock and stone!', 'Lock and load!'),
  (r'My life for Auraxis\.', 'My light endures.'),
  (r'My life for Aiur\.', 'My light endures.'),
  (r'Yamato, fire!', 'Keystone lance, free!'),
  (r'Yamato', 'Keystone Lance'),
  (r'Vespene', 'Volcite'),
  (r'vespene', 'volcite'),
  (r'CAD\. Reactor', 'Vita Reactor'),
  (r'Caduceus Reactor', 'Vita Reactor'),
  (r'caduceusReactor', 'vitaReactor'),
  (r'Caduceus', 'Vita'),
  (r'Singularity Charge', 'Core Charge'),
  (r'Personal Cloaking Field', 'Refraction Field'),
  (r'Metabolic Boost', 'Frenzy Glands'),
  (r'Piercing Claw', 'Rending Fang'),
  (r'Leg Enhancements', 'Stride Matrix'),
  (r'Particle Bay', 'Arc Emitter'),
  (r'Hi-Senal Tracking', 'Phase Calibration'),
  (r'Anima Spore', 'Spore Lance'),
  # ---- race tokens ----
  (r'PROTOSS', 'AURAXIS'),
  (r'Protoss', 'Auraxis'),
  (r'ZERG', 'SKARN'),
  (r'Zerg', 'Skarn'),
  (r'zerg(?=[A-Z_])', 'skarn'),
  (r'protoss(?=[A-Z_])', 'auraxis'),
  (r"'zerg'", "'skarn'"),
  (r"'protoss'", "'auraxis'"),
  (r'zerg', 'skarn'),
  (r'protoss', 'auraxis'),
  # ---- skarn units/structures ----
  (r'zereling', 'skarnling'),
  (r'Zergling', 'Skarnling'),
  (r'zergling', 'skarnling'),
  (r'Hydralisk Den', 'Spine Warren'),
  (r'hydraliskDen', 'spineWarren'),
  (r'Hydralisk', 'Razorspine'),
  (r"icon: 'hydra'", "icon: 'razor'"),
  (r"'hydra'", "'razor'"),
  (r'hydralisk', 'razorspine'),
  (w('hydra'), 'razor'),
  (r'Mutalisk', 'Vexwing'),
  (r"icon: 'muta'", "icon: 'vex'"),
  (r'mutalisk', 'vexwing'),
  (w('muta'), 'vex'),
  (r'Ultralisk Cavern', 'Tremor Cavern'),
  (r'ultraliskCavern', 'tremorCavern'),
  (r'Ultralisk', 'Tremorclaw'),
  (r"icon: 'ultra'", "icon: 'tremor'"),
  (r'ultralisk', 'tremorclaw'),
  (w('ultra'), 'tremor'),
  (r'Overlord', 'Skywarden'),
  (r'overlord(?=[A-Z_])', 'skywarden'),
  (r"icon: 'overlord'", "icon: 'skywarden'"),
  (r'overlord', 'skywarden'),
  (r'Scourge', 'Airstinger'),
  (r'scourge', 'airstinger'),
  (r'Lurker Aspect', 'Burrower Chrysalis'),
  (r'Lurker Egg Research', 'Burrower Chrysalis'),
  (r'lurkerEggZ', 'burrowChrysalisZ'),
  (r'lurkerEgg', 'burrowChrysalis'),
  (r'Lurker', 'Burrower'),
  (r'lurker(?=[A-Z_])', 'burrower'),
  (r"icon: 'lurker'", "icon: 'burrower'"),
  (r'lurker', 'burrower'),
  (r'Hatchery', 'Brood Nest'),
  (r'hatchery(?=[A-Z_])', 'broodNest'),
  (r'hatchery', 'broodNest'),
  (r'\bLair\b', 'Deep Warren'),
  (r"'lair'", "'deepWarren'"),
  (r'\blair\b', 'deepWarren'),
  (r'\bSpire\b', 'Aerie'),
  (r'\bspire\b', 'aerie'),
  (r"'bc'", "'battlecruiser'"),
  # skarn worker 'Drone' renamed to free the name for the new TERRAN drone unit
  (r'\bDrone\b', 'Skarling'),
  (r"icon: 'drone'", "icon: 'skarling'"),
  (r'drone(?=[A-Z_])', 'skarling'),
  (r"'drone'", "'skarling'"),
  (r'\bdrone\b', 'skarling'),
  (r'Extractor', 'Gas Siphon'),
  (r'extractor(?=[A-Z_])', 'gasSiphon'),
  (r'extractor', 'gasSiphon'),
  (r'Greater Spire', 'Sky Aerie'),
  (r'greaterSpire', 'greaterAerie'),
  (r'Spawning Pool', 'Claw Pit'),
  (r'spawningPool', 'clawPit'),
  (r'Evolution Chamber', 'Gene Forge'),
  (r'evolutionChamber', 'geneForge'),
  (r'Spore Colony', 'Stinger Colony'),
  (r'sporeColony', 'stingerColony'),
  (r'Creep Colony', 'Blight Node'),
  (r'creepColony', 'blightNode'),
  (r'Guardian', 'Sporecaster'),
  (r'guardian(?=[A-Z_])', 'sporecaster'),
  (r'guardian', 'sporecaster'),
  (r'Devourer', 'Corroder'),
  (r'devourer(?=[A-Z_])', 'corroder'),
  (r'devourer', 'corroder'),
  (r'broodling', 'hatchling'),
  (r'Broodling', 'Hatchling'),
  # ---- auraxis units/structures ----
  (r'Nexus', 'Aegis'),
  (r'nexus(?=[A-Z_])', 'aegis'),
  (r'nexus', 'aegis'),
  (r'Pylon', 'Conduit'),
  (r'pylon(?=[A-Z_])', 'conduit'),
  (r'pylon', 'conduit'),
  (r'Assimilator', 'Essence Tap'),
  (r'assimilator(?=[A-Z_])', 'essenceTap'),
  (r'assimilator', 'essenceTap'),
  (r'Cybernetics Core', 'Synapse Core'),
  (r'cyberneticsCore', 'synapseCore'),
  (r'Robotics Tech Bay', 'Runeworks'),
  (r'roboticsTechFacility', 'runeworks'),
  (r'Robotics Facility', 'Fabricator Bay'),
  (r'roboticsFacilityTech', 'fabricatorCalibration'),
  (r'roboticsFacility', 'fabricator'),
  (r'Warp Gate', 'Phase Gate'),
  (r'gatewayWarp', 'portalPhase'),
  (r'Stargate', 'Sky Portal'),
  (r'stargate(?=[A-Z_])', 'skyPortal'),
  (r'stargate', 'skyPortal'),
  (r'Fleet Beacon', 'Sky Anchor'),
  (r'fleetBeacon', 'skyAnchor'),
  (r'Photon Cannon', 'Lance Turret'),
  (r'photonCannon', 'lanceTurret'),
  (r'\bForge\b', 'Foundry'),
  (r"'forge'", "'foundry'"),
  (r'Gateway', 'Portal'),
  (r'gateway(?=[A-Z_])', 'portal'),
  (r'gateway', 'portal'),
  (r'Carrier', 'Ark'),
  (r"icon: 'carrier'", "icon: 'ark'"),
  (r'carrier(?=[A-Z_])', 'ark'),
  (r'carrier', 'ark'),
  (r'Corsair', 'Voidlance'),
  (r'corsair(?=[A-Z_])', 'voidlance'),
  (r"icon: 'corsair'", "icon: 'voidlance'"),
  (r'corsair', 'voidlance'),
  (r'Zealot', 'Bladeguard'),
  (r'zealot(?=[A-Z_])', 'bladeguard'),
  (r'zealotSpeed', 'bladeguardSpeed'),
  (r"icon: 'zealot'", "icon: 'bladeguard'"),
  (r'zealot', 'bladeguard'),
  (r'Dragoon', 'Sentinel'),
  (r'dragoonRange', 'sentinelRange'),
  (r'dragoon(?=[A-Z_])', 'sentinel'),
  (r"icon: 'dragoon'", "icon: 'sentinel'"),
  (r'dragoon', 'sentinel'),
  (r'Probe', 'Artificer'),
  (r'probe(?=[A-Z_])', 'artificer'),
  (r"icon: 'probe'", "icon: 'artificer'"),
  (r'probes', 'artificers'),
  (r'probe', 'artificer'),
  (r"\bcouncil\b", 'convocation'),
  (r"'council'", "'convocation'"),
  (r'council(?=[A-Z_])', 'convocation'),
  # ---- terran distinctive (keep Terran identity) ----
  (r'\bSCV\b', 'Rigger'),
  (r"'scv'", "'rigger'"),
  (r'scv(?=[A-Z_\'])', 'rigger'),
  (r'\bscv\b', 'rigger'),
  (r"icon: 'scv'", "icon: 'rigger'"),
  (r'Firebat', 'Incinerator'),
  (r'firebat(?=[A-Z_\'])', 'incinerator'),
  (r"icon: 'firebat'", "icon: 'incinerator'"),
  (r'firebat', 'incinerator'),
  (r'Vulture', 'Duster'),
  (r'vulture(?=[A-Z_\'])', 'duster'),
  (r"icon: 'vulture'", "icon: 'duster'"),
  (r'vulture', 'duster'),
  (r'Goliath', 'Ballista'),
  (r'goliath(?=[A-Z_\'])', 'ballista'),
  (r"icon: 'goliath'", "icon: 'ballista'"),
  (r'goliath', 'ballista'),
  (r'Siege Tank', 'Siebreaker'),
  (r"icon: 'tank'", "icon: 'tank'"),
  # texture key renames for art.js map keys (bare identifiers in object literals)
  (w('bc'), 'battlecruiser'),
  (w('scv'), 'rigger'),
  (w('firebat'), 'incinerator'),
  (w('vulture'), 'duster'),
  (w('goliath'), 'ballista'),
  # generic bio/creep terminology (keep gameplay term 'blight' for the organic carpet)
  (r'creep(?=[A-Z_])', 'blight'),
  (r'Creep', 'Blight'),
  (r'\bcreeps\b', 'blight'),
  (r'\bcreep\b', 'blight'),
]

TRADEMARKS = ['zerg','protoss','starcraft','kerrigan','overmind','cerebrate','aiur',
  'vespene','caduceus','yamato','daealaam','zereling','hydralisk','mutalisk','ultralisk',
  'spawning pool','evolution chamber','templar','firebat','scv','stargate','dark archon',
  'high templar','overlord','scourge','lurker','nexus','pylon','assimilator','dragoon',
  'zealot','carrier','corsair','probe','xel','aiur']

total = {}
for f in FILES:
    src = f.read_text()
    out = src
    for pat, rep in RULES:
        out, n = re.subn(pat, rep, out)
        if n: total[pat] = total.get(pat, 0) + n
    if out != src:
        f.write_text(out)
        print('patched', f.relative_to(ROOT))

print('--- residual trademark hits ---')
res = 0
for f in FILES + [ROOT/'index.html']:
    if not f.exists(): continue
    t = f.read_text().lower()
    for tm in TRADEMARKS:
        c = t.count(tm)
        if c:
            print(f.relative_to(ROOT), tm, c); res += c
print('RESIDUAL_TOTAL', res)
